use std::sync::Arc;

use crate::StringDatabase;

pub struct ClientStrings {
    pub invalid_name: String,
    pub duration_seconds: String,

    pub equip_require_job: String,
    pub item_class: String,
    pub item_durability: String,
    pub item_life: String,
    pub item_quality: String,
    pub item_attack_range: String,
    pub item_attack_speed_fast: String,
    pub item_attack_speed_normal: String,
    pub item_attack_speed_slow: String,
    pub item_move_speed: String,
    pub item_weight: String,
    pub item_requires_appraisal: String,

    pub skill_level: String,
    pub skill_damage_type_0: String,
    pub skill_damage_type_1: String,
    pub skill_damage_type_2: String,
    pub skill_damage_type_3: String,
    pub skill_cast_range: String,
    pub skill_aoe_range: String,
    pub skill_cost_ability: String,
    pub skill_learn_point_cost: String,
    pub skill_require_ability: String,
    pub skill_summon_point_cost: String,
    pub skill_steal_ability: String,
    pub skill_require_equipment: String,
    pub skill_require_job: String,
    pub skill_require_skill: String,
    pub skill_status_effects: String,
    pub skill_success_rate: String,
    pub skill_duration: String,
    pub skill_recover_xp: String,
    pub skill_passive_ability: String,
    pub skill_next_level_info: String,
    pub skill_power: String,
    pub skill_target: String,
    pub skill_type: String,

    pub bank_tab: String,
    pub bank_tab_premium: String,

    pub clan_name: String,
    pub clan_level: String,
    pub clan_point: String,
    pub clan_slogan: String,
    pub clan_money: String,
    pub clan_ally: String,
    pub clan_member_contribution: String,
    pub clan_member_count: String,
    pub clan_promote_error: String,
    pub clan_created: String,
    pub clan_joined: String,
    pub clan_destroy_success: String,
    pub clan_create_error: String,
    pub clan_create_error_name: String,
    pub clan_create_error_permission: String,
    pub clan_destroyed: String,
    pub clan_destroy_error: String,
    pub clan_destroy_error_permission: String,
    pub clan_join_member_accepted: String,
    pub clan_join_error: String,
    pub clan_join_error_permission: String,
    pub clan_join_error_already_in_clan: String,
    pub clan_kick_success: String,
    pub clan_kicked: String,
    pub clan_quit: String,
    pub clan_invited: String,
    pub clan_invite_rejected: String,
    pub clan_create_error_condition: String,
    pub clan_create_conditions: String,
    pub clan_create_error_slogan: String,
    pub clan_error_permission: String,

    pub _string_database: Arc<StringDatabase>,
}
